# This is a code section from the cytofkit package (Artistic License 2.0) provided solely for reproducibility. 
# Please refer to the original source for any other usage: https://github.com/JinmiaoChenLab/cytofkit

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jaccard_coeff <- function(idx) {
    .Call('cytofkit_jaccard_coeff', PACKAGE = 'cytofkit', idx)
}

